apiVersion: v1
kind: Service
metadata:
  name: app-service-lb-payment
spec:
  selector:
    app: fiap-payment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: LoadBalancer