apiVersion: v1
kind: Service
metadata:
  name: app-service-payment
spec:
  selector:
    app: fiap-payment-app
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3000
      nodePort: 30007
  type: NodePort
